version: '2'

services:
  postgresdb:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: socialhub_db
      POSTGRES_USER: socialhub_user
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -U socialhub_user || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      postgresdb:
        condition: service_healthy
    volumes:
      - .:/socialhub/app


volumes:
  pg_data:
